# Config para desplegar SOLO el worker: `cd musgo_astro/worker && npx wrangler deploy`
name = "musgoesp32"
main = "index.js"
compatibility_date = "2024-11-01"

account_id = "dac9003257ad1248eac7396e1715b05c"

[[kv_namespaces]]
binding = "MUSGO_DATA"
id = "9a597ef934e140beaf116089c19d3544"
